### ISSUE TITLE
map_update purpose

### ISSUE THREAD

**Issue by roboticsai** [neobotix/neo_localization#4]
I was studying the soruce code of this package, i'm little new in relocalization. When i saw the neo_localization_node.cpp file i couldn't understand what is the purpose of map_update. I visualized the map_tile in rviz and found that this map is same as that of real map.

**Comment by madMAx43v3r** [comment]
For small maps it's the same yes. On bigger maps you will see that it's a local tile around the current robot position. The reason for using a tile is memory consumption, because the algorithm needs the grid map in 32-bit float format, but we don't want to store the entire map in float format in memory.

Having the tile ready in 32-bit float makes it much more efficient since we don't have to convert 8-bit integer to float for every computation.

**Comment by padhupradheep** [comment]
Closing the issue, as I believe the question is answered!
